import fs from "node:fs";
import path from "node:path";
import type { ReactNode } from "react";

export const metadata = {
  title: "Methodology -- Pricing the Heat",
};

// docs/STATEWISE_RESULTS.md is machine-generated by the batch pipeline (see
// its own header) -- this page PARSES its real pipe tables and renders them,
// rather than hand-maintaining a duplicate copy that could drift out of sync
// with the real per-state contract.json results.
const STATEWISE_MD_PATH = path.join(process.cwd(), "..", "docs", "STATEWISE_RESULTS.md");

type MdTable = { headers: string[]; rows: string[][] };

function splitRow(line: string): string[] {
  const trimmed = line.trim();
  const inner = trimmed.startsWith("|") && trimmed.endsWith("|") ? trimmed.slice(1, -1) : trimmed;
  return inner.split("|").map((cell) => cell.trim());
}

/** Extracts every contiguous block of `| ... |` lines in the markdown as a
 * table (header row, then a `---` separator row, then data rows). */
function extractTables(markdown: string): MdTable[] {
  const lines = markdown.split("\n");
  const tables: MdTable[] = [];
  let block: string[] = [];
  for (const line of lines) {
    if (line.trim().startsWith("|")) {
      block.push(line);
    } else if (block.length > 0) {
      if (block.length >= 2) tables.push({ headers: splitRow(block[0]), rows: block.slice(2).map(splitRow) });
      block = [];
    }
  }
  if (block.length >= 2) tables.push({ headers: splitRow(block[0]), rows: block.slice(2).map(splitRow) });
  return tables;
}

/** Renders a markdown cell's inline **bold** and `code` spans -- the only
 * inline markdown the generator actually emits (see docs/STATEWISE_RESULTS.md). */
function renderInlineMd(text: string): ReactNode {
  const parts: ReactNode[] = [];
  const regex = /(\*\*[^*]+\*\*|`[^`]+`)/g;
  let lastIndex = 0;
  let match: RegExpExecArray | null;
  let key = 0;
  while ((match = regex.exec(text)) !== null) {
    if (match.index > lastIndex) parts.push(text.slice(lastIndex, match.index));
    const token = match[0];
    if (token.startsWith("**")) {
      parts.push(<strong key={key++}>{token.slice(2, -2)}</strong>);
    } else {
      parts.push(
        <code key={key++} className="text-xs bg-gray-100 px-1 py-0.5 rounded">
          {token.slice(1, -1)}
        </code>,
      );
    }
    lastIndex = regex.lastIndex;
  }
  if (lastIndex < text.length) parts.push(text.slice(lastIndex));
  return parts;
}

function MdTableView({ table }: { table: MdTable }) {
  return (
    <div className="overflow-x-auto border border-gray-200 rounded">
      <table className="min-w-full text-xs">
        <thead className="bg-gray-50">
          <tr>
            {table.headers.map((h, i) => (
              <th key={i} className="px-3 py-2 text-left font-medium text-gray-600 whitespace-nowrap">
                {renderInlineMd(h)}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {table.rows.map((row, i) => (
            <tr key={i} className={i % 2 === 0 ? "bg-white" : "bg-gray-50/50"}>
              {row.map((cell, j) => (
                <td key={j} className="px-3 py-1.5 whitespace-nowrap text-gray-800">
                  {renderInlineMd(cell)}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default function MethodologyPage() {
  let statewiseMd: string | null = null;
  let loadError: string | null = null;
  try {
    statewiseMd = fs.readFileSync(STATEWISE_MD_PATH, "utf-8");
  } catch {
    loadError =
      "Could not load docs/STATEWISE_RESULTS.md at build time -- no results table is shown rather " +
      "than fabricating one.";
  }

  const tables = statewiseMd ? extractTables(statewiseMd) : [];
  const pricedTable = tables[0] ?? null;
  const excludedTable = tables[1] ?? null;
  const generatedMatch = statewiseMd?.match(/_Generated ([^_]+)_/);
  const gridCeilingMatch = statewiseMd?.match(/\*\*Grid-ceiling audit\*\*: (.+)/);

  return (
    <main className="max-w-4xl mx-auto p-4 sm:p-6 space-y-8">
      <div>
        <h1 className="text-xl font-semibold mb-3">How this works</h1>
        <p className="text-sm text-gray-700 leading-relaxed">
          <strong>Pricing the Heat</strong> is a parametric micro-insurance product for informal
          outdoor workers -- street vendors, construction workers, delivery riders -- across 79
          Indian and US states, priced from each state&rsquo;s own real weather, wages, and climate
          regime. It is never one product framed the same way everywhere: some states see chronic,
          frequent heat wage-loss and are priced as <strong>high-frequency income smoothing</strong>;
          others see rare, extreme heat spikes and are priced as{" "}
          <strong>catastrophe insurance</strong> instead -- discovered per state from the real ten-year
          history, never assumed globally.
        </p>
      </div>

      <section>
        <h2 className="text-base font-semibold mb-2">1. Where the heat comes from</h2>
        <p className="text-sm text-gray-700 leading-relaxed">
          A small graph neural network (an STGCN, spatio-temporal graph convolution) forecasts
          street-level heat (shade-WBGT) at every real weather-station grid cell around each state&rsquo;s
          anchor metro, from NASA POWER&rsquo;s public API -- no synthetic weather anywhere in the
          pipeline.
        </p>
      </section>

      <section>
        <h2 className="text-base font-semibold mb-2">2. How wage loss is modeled</h2>
        <p className="text-sm text-gray-700 leading-relaxed">
          A behavioral simulation of individual workers (a multi-agent POMDP trained with
          reinforcement learning) models how a worker facing heat actually trades off income against
          heat exposure, calibrated against a cited wage-loss elasticity from published
          occupational-heat-stress literature (~2.6% wage loss per degree above a WBGT threshold,
          ~0.57%/degree for construction). Baseline daily wages are each state&rsquo;s own real, legislated
          minimum-wage schedule -- cited, but <strong>unverified pending human confirmation</strong>, and
          the app says so honestly rather than implying they have been independently checked.
        </p>
      </section>

      <section>
        <h2 className="text-base font-semibold mb-2">3. Fusing heat and loss into one index</h2>
        <p className="text-sm text-gray-700 leading-relaxed">
          A Gumbel survival copula fuses each state&rsquo;s heat trigger with its workers&rsquo; modeled
          wage loss into the <strong>mu-TEVI index</strong> (0-100) -- the single number the insurance
          contract actually pays out on. Because the contract pays on an INDEX rather than an
          assessment of any individual&rsquo;s actual loss, there is always a gap between the two:{" "}
          <strong>basis risk</strong>. We measure and disclose it on every quote rather than hiding it.
        </p>
      </section>

      <section>
        <h2 className="text-base font-semibold mb-2">4. Pricing the contract, per state</h2>
        <p className="text-sm text-gray-700 leading-relaxed">
          A Longstaff-Schwartz Monte Carlo pricer (an option-pricing technique for a one-shot,
          optimally-timed claim) prices each state&rsquo;s policy from its own fitted joint distribution,
          then a Wang transform loads a real insurer&rsquo;s risk margin on top of the fair actuarial
          price. Each state&rsquo;s strike/window and frame (income smoothing vs. catastrophe insurance)
          are chosen on that state&rsquo;s own real historical replay -- see the table below.
        </p>
      </section>

      <section>
        <h2 className="text-base font-semibold mb-2">A bug we found and fixed before publication</h2>
        <p className="text-sm text-gray-700 leading-relaxed">
          A strike-truncation bug desynced 33 of 78 states&rsquo; reported contracts from their real
          priced economics, and a related grid-ceiling issue censored a handful of heat-concentrated
          states&rsquo; true optimal strike. Both were root-caused and fixed together -- three states
          (Washington, Oregon, Colorado) had spurious negative MAE-vs-baseline results that flipped
          positive once corrected. We surface this as a strength, not something to hide: see{" "}
          <code className="text-xs bg-gray-100 px-1 py-0.5 rounded">docs/KNOWN_ISSUES_RESOLVED.md</code>{" "}
          in the repository for the full root-cause record.
        </p>
      </section>

      <section>
        <h2 className="text-base font-semibold mb-2">State-wise results</h2>
        {loadError && (
          <p className="text-sm text-amber-700 border border-amber-200 bg-amber-50 rounded p-3">
            {loadError}
          </p>
        )}
        {generatedMatch && (
          <p className="text-xs text-gray-500 mb-2">Generated {generatedMatch[1]}</p>
        )}
        {pricedTable && <MdTableView table={pricedTable} />}
        {gridCeilingMatch && (
          <p className="text-xs text-gray-500 mt-2">{gridCeilingMatch[1]}</p>
        )}
      </section>

      <section>
        <h2 className="text-base font-semibold mb-2">Excluded states</h2>
        <p className="text-sm text-gray-700 leading-relaxed mb-2">
          A state is excluded when it has too few real heat-exposure days to fit a defensible
          wage-loss distribution -- a documented coverage boundary, never a silent gap.
        </p>
        {excludedTable && <MdTableView table={excludedTable} />}
      </section>

      <section>
        <h2 className="text-base font-semibold mb-2">Data provenance</h2>
        <ul className="text-sm text-gray-700 leading-relaxed list-disc list-inside space-y-1">
          <li>Heat: NASA POWER regional API (real fetches, cached and recorded with provenance sidecars).</li>
          <li>Wages (labor structure): World Bank Indicators API v2.</li>
          <li>Baseline daily wages: each state&rsquo;s own cited public minimum-wage schedule.</li>
          <li>Elasticity: cited occupational heat-stress literature -- the one labeled modeling assumption.</li>
        </ul>
      </section>
    </main>
  );
}
